services:
  # Backend API
  - type: web
    name: ecommerce-recommender-api
    env: python
    region: singapore
    plan: free
    branch: main
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.11"
